version: 0.1
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket vmwcloud-codepipeline-lambda 
                                   --s3-prefix node-lambda --output-template-file NewSamTemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yml