AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeLosAngeles:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./los_angeles
      Events:
        getTime:
          Type: Api
          Properties:
            Path: /los_angeles
            Method: GET
  TimeSaoPaulo:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./sao_paulo
      Events:
        getTime:
          Type: Api
          Properties:
            Path: /sao_paulo
            Method: GET